"""Create clear ROI postprocessing plots from ``roi_summary.csv``.

The plotting code is intentionally direct and thesis-script friendly:

1. Read ROI summary rows generated by ``roi_postprocessing.py``.
2. Read the global force/displacement CSV so each frame title can report where
   it sits in the loading cycle.
3. Save full technical plots and simplified representative-ROI plots.
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROI_RE = re.compile(r"roi_(left|right)_(\d+)$")
PHASE_COLUMNS = ["Phase 0", "Phase 1", "Phase 2", "Phase 3"]
PHASE_COLORS = ["#4C78A8", "#F58518", "#54A24B", "#B279A2"]
STRESS_COLOR = "#6A3D9A"
PLASTIC_COLOR = "#4D4D4D"
LOW_STRESS_COLOR = "#1F77B4"
HIGH_STRESS_COLOR = "#D62728"
YOUNGS_MODULUS_MPA = 71000.0


@dataclass(frozen=True)
class FrameContext:
    frame_number: int | None
    step_time: float
    global_strain: float
    global_stress: float
    global_plastic_strain: float


@dataclass(frozen=True)
class RepresentativeSelection:
    low_stress_high_plastic_roi: str
    high_stress_low_plastic_roi: str
    metrics: pd.DataFrame


def parse_roi_name(roi_name: str) -> tuple[str, int]:
    match = ROI_RE.match(str(roi_name))
    if not match:
        raise ValueError(f"ROI name must look like roi_left_01 or roi_right_01: {roi_name}")
    side, number = match.groups()
    return side, int(number)


def format_roi_label(roi_name: str) -> str:
    """Convert ``roi_left_01`` to ``Left roi 01`` for plot labels."""
    side, number = parse_roi_name(roi_name)
    return f"{side.capitalize()} roi {number:02d}"


def ordered_roi_names(roi_names, mode: str = "grouped_by_side") -> list[str]:
    """Return ROI names in one of the two requested presentation orders."""
    names = sorted(set(str(name) for name in roi_names), key=lambda name: (parse_roi_name(name)[0], parse_roi_name(name)[1]))
    if mode == "grouped_by_side":
        side_rank = {"left": 0, "right": 1}
        return sorted(names, key=lambda name: (side_rank[parse_roi_name(name)[0]], parse_roi_name(name)[1]))
    if mode == "paired_by_height":
        side_rank = {"left": 0, "right": 1}
        return sorted(names, key=lambda name: (parse_roi_name(name)[1], side_rank[parse_roi_name(name)[0]]))
    raise ValueError(f"Unknown ROI ordering mode: {mode}")


def read_global_cycle_csv(cycle_csv: str | Path) -> pd.DataFrame:
    """Read the global cycle CSV written by getForceDisp.py."""
    cycle_path = Path(cycle_csv)
    return pd.read_csv(cycle_path, skiprows=2).dropna(how="all")


def frame_context_from_cycle_csv(
    cycle_csv: str | Path,
    step_time: float,
    frame_number: int | None = None,
    youngs_modulus_mpa: float = YOUNGS_MODULUS_MPA,
) -> FrameContext:
    """Find the nearest global cycle row and compute global plastic strain amplitude."""
    cycle_data = read_global_cycle_csv(cycle_csv)
    row_index = (cycle_data["Step Time"].astype(float) - float(step_time)).abs().idxmin()
    row = cycle_data.loc[row_index]
    global_strain = float(row["U_Y"])
    global_stress = float(row["Total RF Y"])
    global_plastic_strain = max(abs(global_strain) - abs(global_stress) / youngs_modulus_mpa, 0.0)
    return FrameContext(
        frame_number=frame_number,
        step_time=float(row["Step Time"]),
        global_strain=global_strain,
        global_stress=global_stress,
        global_plastic_strain=global_plastic_strain,
    )


def build_frame_title(prefix: str, frame_number: int, step_time: float, global_strain: float) -> str:
    """Build a title that makes the cycle location explicit."""
    return f"{prefix} — Frame {frame_number}, Step time {step_time:.3f}, global strain {global_strain:+.4f}"


def select_representative_rois(
    frame_data: pd.DataFrame,
    global_stress: float,
    global_plastic_strain: float,
) -> RepresentativeSelection:
    """Select contrasting ROIs using absolute stress magnitude ratios.

    Low-stress/high-plastic score favors low |local stress| / |global stress| and
    high local plastic strain / global plastic strain.  High-stress/low-plastic
    score does the opposite.
    """
    metrics = frame_data.set_index("roi_name").copy()
    stress_denominator = abs(float(global_stress))
    if math.isclose(stress_denominator, 0.0):
        stress_denominator = max(metrics["average_stress_mpa"].abs().max(), 1.0)
    plastic_denominator = float(global_plastic_strain)
    if math.isclose(plastic_denominator, 0.0):
        plastic_denominator = max(metrics["average_plastic_strain"].max(), 1.0e-12)

    metrics["stress_ratio"] = metrics["average_stress_mpa"].abs() / stress_denominator
    metrics["plastic_ratio"] = metrics["average_plastic_strain"] / plastic_denominator
    metrics["low_stress_high_plastic_score"] = metrics["plastic_ratio"] / metrics["stress_ratio"].replace(0.0, np.nan)
    metrics["high_stress_low_plastic_score"] = metrics["stress_ratio"] / metrics["plastic_ratio"].replace(0.0, np.nan)
    metrics = metrics.replace([np.inf, -np.inf], np.nan).fillna(0.0)

    low_candidates = metrics[metrics["stress_ratio"] < 1.0]
    if low_candidates.empty:
        # If all ROIs are above the global stress magnitude, still choose the
        # best explanatory contrast by balancing high plasticity against stress.
        low_high = str(metrics["low_stress_high_plastic_score"].idxmax())
    else:
        low_high = str(low_candidates["plastic_ratio"].idxmax())

    high_candidates = metrics[metrics["stress_ratio"] > 1.0]
    if low_high in high_candidates.index:
        high_candidates = high_candidates.drop(index=low_high)
    if high_candidates.empty:
        high_candidates = metrics.drop(index=low_high)
        high_low = str(high_candidates["high_stress_low_plastic_score"].idxmax())
    else:
        high_low = str(high_candidates["plastic_ratio"].idxmin())
    return RepresentativeSelection(low_high, high_low, metrics)


def _save_figure(fig, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".svg"), bbox_inches="tight")
    plt.close(fig)


def _apply_group_shading(ax, order: list[str], mode: str, enabled: bool) -> None:
    if not enabled:
        return
    if mode == "grouped_by_side":
        left_count = sum(1 for name in order if parse_roi_name(name)[0] == "left")
        ax.axvspan(-0.5, left_count - 0.5, color="#EAF2F8", alpha=0.75, zorder=0)
        ax.axvspan(left_count - 0.5, len(order) - 0.5, color="#FDEDEC", alpha=0.60, zorder=0)
        ax.text((left_count - 1) / 2, 0.98, "Left edge", transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=9)
        ax.text((left_count + len(order) - 1) / 2, 0.98, "Right edge", transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=9)
    elif mode == "paired_by_height":
        for pair_start in range(0, len(order), 2):
            if (pair_start // 2) % 2 == 0:
                ax.axvspan(pair_start - 0.5, pair_start + 1.5, color="#F4F6F7", alpha=0.75, zorder=0)


def plot_full_response(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
    mode: str,
    shaded_bands: bool = True,
) -> Path:
    """Create the multi-panel full technical ROI response plot."""
    order = ordered_roi_names(frame_data["roi_name"], mode=mode)
    data = frame_data.set_index("roi_name").loc[order]
    x = np.arange(len(order))
    labels = [format_roi_label(name) for name in order]

    fig, axes = plt.subplots(3, 1, figsize=(max(12, 0.62 * len(order)), 11), sharex=True, gridspec_kw={"height_ratios": [1.0, 1.0, 1.25]})
    title_mode = "Grouped by side" if mode == "grouped_by_side" else "Paired by vertical position"
    fig.suptitle(build_frame_title(f"ROI response and phase fractions ({title_mode})", int(context.frame_number), context.step_time, context.global_strain), fontsize=14, y=0.995)

    # Stress panel
    axes[0].plot(x, data["average_stress_mpa"], marker="o", color=STRESS_COLOR, linewidth=2.0, label="ROI average S22")
    axes[0].axhline(context.global_stress, color=STRESS_COLOR, linestyle="--", linewidth=1.4, label="Global stress")
    axes[0].set_ylabel("Stress S22 (MPa)")
    axes[0].grid(True, axis="y", alpha=0.3)
    axes[0].legend(loc="best")

    # Plastic strain panel
    plastic_values = data["average_plastic_strain"].clip(lower=1.0e-12)
    axes[1].plot(x, plastic_values, marker="s", color=PLASTIC_COLOR, linewidth=2.0, label="ROI average plastic strain")
    if context.global_plastic_strain > 0.0:
        axes[1].axhline(context.global_plastic_strain, color=PLASTIC_COLOR, linestyle="--", linewidth=1.4, label="Global plastic strain estimate")
    axes[1].set_yscale("log")
    axes[1].set_ylabel("Plastic strain\n(log scale)")
    axes[1].grid(True, axis="y", alpha=0.3, which="both")
    axes[1].legend(loc="best")

    # Phase fractions panel
    bottom = np.zeros(len(order))
    for phase, color in zip(PHASE_COLUMNS, PHASE_COLORS):
        values = data[phase].to_numpy(dtype=float)
        axes[2].bar(x, values, bottom=bottom, color=color, label=phase, width=0.72)
        bottom += values
    axes[2].set_ylabel("Phase fraction (%)")
    axes[2].set_ylim(0, 100)
    axes[2].grid(True, axis="y", alpha=0.25)
    axes[2].legend(ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.42))

    for ax in axes:
        _apply_group_shading(ax, order, mode, shaded_bands)
        ax.set_xlim(-0.5, len(order) - 0.5)

    axes[2].set_xticks(x)
    axes[2].set_xticklabels(labels, rotation=45, ha="right")
    axes[2].set_xlabel("Region of interest")
    fig.tight_layout(rect=[0, 0.04, 1, 0.965])

    output = Path(output_path)
    _save_figure(fig, output)
    return output


def plot_representative_comparison(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
) -> Path:
    """Create the two-ROI explanatory plot with normalized response and phases."""
    selection = select_representative_rois(frame_data, context.global_stress, context.global_plastic_strain)
    selected_names = [selection.low_stress_high_plastic_roi, selection.high_stress_low_plastic_roi]
    labels = [format_roi_label(name) for name in selected_names]
    metrics = selection.metrics.loc[selected_names]
    phase_data = frame_data.set_index("roi_name").loc[selected_names, PHASE_COLUMNS]

    fig, axes = plt.subplots(1, 2, figsize=(11, 5.8), gridspec_kw={"width_ratios": [1.05, 1.0]})
    fig.suptitle(build_frame_title("Two representative ROI responses", int(context.frame_number), context.step_time, context.global_strain), fontsize=14)

    # Normalized response bars
    x = np.arange(len(selected_names))
    width = 0.34
    axes[0].bar(x - width / 2, metrics["stress_ratio"], width=width, color=STRESS_COLOR, label="|ROI stress| / |global stress|")
    axes[0].bar(x + width / 2, metrics["plastic_ratio"], width=width, color=PLASTIC_COLOR, label="ROI plastic strain / global estimate")
    axes[0].axhline(1.0, color="black", linestyle="--", linewidth=1.0, alpha=0.8)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(labels, rotation=20, ha="right")
    axes[0].set_ylabel("Normalized value")
    axes[0].set_title("Mechanical response relative to global cycle")
    axes[0].grid(True, axis="y", alpha=0.3)
    axes[0].legend(fontsize=8, loc="upper center", bbox_to_anchor=(0.5, -0.16))
    annotation_y = axes[0].get_ylim()[1] * 0.90
    text_box = {"boxstyle": "round,pad=0.25", "facecolor": "white", "edgecolor": "none", "alpha": 0.75}
    axes[0].text(x[0], annotation_y, "Lower stress\nhigher plastic", ha="center", va="top", color=LOW_STRESS_COLOR, fontsize=9, bbox=text_box)
    axes[0].text(x[1], annotation_y, "Higher stress\nlower plastic", ha="center", va="top", color=HIGH_STRESS_COLOR, fontsize=9, bbox=text_box)

    # Phase fractions for selected ROIs
    bottom = np.zeros(len(selected_names))
    for phase, color in zip(PHASE_COLUMNS, PHASE_COLORS):
        values = phase_data[phase].to_numpy(dtype=float)
        axes[1].bar(x, values, bottom=bottom, color=color, label=phase, width=0.55)
        bottom += values
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(labels, rotation=20, ha="right")
    axes[1].set_ylabel("Phase fraction (%)")
    axes[1].set_ylim(0, 100)
    axes[1].set_title("Local phase / volume fractions")
    axes[1].grid(True, axis="y", alpha=0.25)
    axes[1].legend(fontsize=8, loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=2)

    fig.tight_layout(rect=[0, 0.06, 1, 0.93])
    output = Path(output_path)
    _save_figure(fig, output)
    return output


def plot_roi_location_map(
    frame_data: pd.DataFrame,
    context: FrameContext,
    output_path: str | Path,
) -> Path:
    """Create a simple domain schematic showing selected representative ROIs."""
    selection = select_representative_rois(frame_data, context.global_stress, context.global_plastic_strain)
    selected = {
        selection.low_stress_high_plastic_roi: (LOW_STRESS_COLOR, "Lower stress / higher plastic"),
        selection.high_stress_low_plastic_roi: (HIGH_STRESS_COLOR, "Higher stress / lower plastic"),
    }

    fig, ax = plt.subplots(figsize=(5.2, 7.2))
    fig.suptitle(build_frame_title("Selected ROI locations", int(context.frame_number), context.step_time, context.global_strain), fontsize=12)
    ax.add_patch(plt.Rectangle((0, 0), 1, 1, fill=False, linewidth=2.0, color="black"))
    ax.arrow(0.5, 1.05, 0, 0.09, width=0.01, head_width=0.05, head_length=0.035, color="black", clip_on=False)
    ax.arrow(0.5, -0.05, 0, -0.09, width=0.01, head_width=0.05, head_length=0.035, color="black", clip_on=False)
    ax.text(0.58, 1.11, "Cyclic loading", fontsize=9, va="center")

    radius = 0.035
    for side in ("left", "right"):
        x = 0.0 if side == "left" else 1.0
        ha = "right" if side == "left" else "left"
        text_dx = -0.04 if side == "left" else 0.04
        for number in range(1, 10):
            roi_name = f"roi_{side}_{number:02d}"
            y = 1.0 - 0.1 - (number - 1) * 0.1
            color, description = selected.get(roi_name, ("#BDBDBD", ""))
            size = radius * (1.6 if roi_name in selected else 1.0)
            ax.add_patch(plt.Circle((x, y), size, color=color, alpha=0.88, ec="black", lw=0.6))
            if roi_name in selected:
                ax.text(x + text_dx, y, f"{format_roi_label(roi_name)}\n{description}", ha=ha, va="center", fontsize=8, color=color)

    ax.set_xlim(-0.35, 1.35)
    ax.set_ylim(-0.18, 1.18)
    ax.set_aspect("equal")
    ax.axis("off")
    output = Path(output_path)
    _save_figure(fig, output)
    return output


def make_all_roi_plots(
    roi_summary_csv: str | Path,
    cycle_csv: str | Path,
    output_root: str | Path,
) -> list[Path]:
    """Generate all requested ROI plot families for every frame in the summary."""
    summary = pd.read_csv(roi_summary_csv)
    output_root = Path(output_root)
    created: list[Path] = []

    for frame_number in sorted(summary["frame_number"].unique()):
        frame_data = summary[summary["frame_number"] == frame_number].copy()
        step_time = float(frame_data["step_time"].iloc[0])
        context = frame_context_from_cycle_csv(cycle_csv, step_time=step_time, frame_number=int(frame_number))
        frame_prefix = f"frame{int(frame_number)}"

        created.append(plot_full_response(
            frame_data,
            context,
            output_root / "full_response" / f"{frame_prefix}_grouped_by_side.png",
            mode="grouped_by_side",
            shaded_bands=True,
        ))
        created.append(plot_full_response(
            frame_data,
            context,
            output_root / "full_response" / f"{frame_prefix}_paired_by_height.png",
            mode="paired_by_height",
            shaded_bands=True,
        ))
        created.append(plot_representative_comparison(
            frame_data,
            context,
            output_root / "representative_rois" / f"{frame_prefix}_representative_roi_comparison.png",
        ))
        created.append(plot_roi_location_map(
            frame_data,
            context,
            output_root / "location_maps" / f"{frame_prefix}_representative_roi_locations.png",
        ))

    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Create ROI response/phase fraction plots.")
    parser.add_argument("--roi-summary", required=True, help="Path to roi_summary.csv")
    parser.add_argument("--cycle-csv", required=True, help="Path to global cycle CSV, e.g. strainRratio-1.csv")
    parser.add_argument("--output-root", required=True, help="Folder where plot families will be saved")
    args = parser.parse_args()

    created = make_all_roi_plots(args.roi_summary, args.cycle_csv, args.output_root)
    print("Created ROI plots:")
    for path in created:
        print(path)
        print(path.with_suffix(".svg"))


if __name__ == "__main__":
    main()
